/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 04 20:12:32 GMT 2026
 */

package com.google.javascript.jscomp;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.google.javascript.jscomp.CodeConsumer;
import com.google.javascript.jscomp.CodeGenerator;
import com.google.javascript.rhino.Node;
import java.nio.charset.Charset;
import java.nio.charset.CharsetEncoder;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CodeGenerator_ESTest extends CodeGenerator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String string0 = CodeGenerator.identifierEscape(" I~NxC`({k2");
      assertEquals(" I~NxC`({k2", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String string0 = CodeGenerator.identifierEscape("\uFEFFbWz\f");
      assertEquals("\\ufeffbWz\\u000c", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Charset charset0 = Charset.defaultCharset();
      assertEquals("UTF-8", charset0.toString());
      assertTrue(charset0.isRegistered());
      assertTrue(charset0.canEncode());
      assertEquals("UTF-8", charset0.displayName());
      assertEquals("UTF-8", charset0.name());
      assertNotNull(charset0);
      
      CharsetEncoder charsetEncoder0 = charset0.newEncoder();
      assertEquals("UTF-8", charset0.toString());
      assertTrue(charset0.isRegistered());
      assertTrue(charset0.canEncode());
      assertEquals("UTF-8", charset0.displayName());
      assertEquals("UTF-8", charset0.name());
      assertEquals(1.1F, charsetEncoder0.averageBytesPerChar(), 0.01F);
      assertEquals(3.0F, charsetEncoder0.maxBytesPerChar(), 0.01F);
      assertNotNull(charsetEncoder0);
      
      String string0 = CodeGenerator.regexpEscape("+Y;.dBCG|ji]>^]d", charsetEncoder0);
      assertEquals("/+Y;.dBCG|ji]>^]d/", string0);
      assertEquals("UTF-8", charset0.toString());
      assertTrue(charset0.isRegistered());
      assertTrue(charset0.canEncode());
      assertEquals("UTF-8", charset0.displayName());
      assertEquals("UTF-8", charset0.name());
      assertEquals(1.1F, charsetEncoder0.averageBytesPerChar(), 0.01F);
      assertEquals(3.0F, charsetEncoder0.maxBytesPerChar(), 0.01F);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String string0 = CodeGenerator.escapeToDoubleQuotedJsString("6t_:/&\"DD,#<!--<*o");
      assertEquals("\"6t_:/&\\\"DD,#<\\!--<*o\"", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String string0 = CodeGenerator.escapeToDoubleQuotedJsString("xf's</script");
      assertEquals("\"xf's<\\/script\"", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      String string0 = CodeGenerator.escapeToDoubleQuotedJsString(">s)P@)2X9P7H");
      assertEquals("\">s)P@)2X\\u007f9P7H\"", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String string0 = CodeGenerator.escapeToDoubleQuotedJsString("3,?Dn>}Y");
      assertEquals("\"3,?Dn>}Y\"", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String string0 = CodeGenerator.escapeToDoubleQuotedJsString("Node cannot be refined. \n");
      assertEquals("\"Node cannot be refined. \\n\"", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CodeGenerator codeGenerator0 = new CodeGenerator((CodeConsumer) null);
      assertNotNull(codeGenerator0);
      
      codeGenerator0.addAllSiblings((Node) null);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CodeGenerator codeGenerator0 = new CodeGenerator((CodeConsumer) null);
      assertNotNull(codeGenerator0);
      
      codeGenerator0.addArrayList((Node) null);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CodeGenerator codeGenerator0 = new CodeGenerator((CodeConsumer) null);
      assertNotNull(codeGenerator0);
      
      Node node0 = new Node(3108);
      assertEquals(48, Node.DIRECTIVES);
      assertEquals(39, Node.EMPTY_BLOCK);
      assertEquals(4, Node.ENUM_PROP);
      assertEquals(31, Node.SIDE_EFFECTS_FLAGS_MASK);
      assertEquals(26, Node.DIRECTCALL_PROP);
      assertEquals(4095, Node.MAX_COLUMN_NUMBER);
      assertEquals(20, Node.FINALLY_PROP);
      assertEquals(4095, Node.COLUMN_MASK);
      assertEquals(24, Node.LASTUSE_PROP);
      assertEquals(17, Node.TYPE_PROP);
      assertEquals((-2), Node.OBJECT_IDS_PROP);
      assertEquals(15, Node.CASEARRAY_PROP);
      assertEquals(35, Node.PARENTHESIZED_PROP);
      assertEquals(38, Node.SYNTHETIC_BLOCK_PROP);
      assertEquals(3, Node.CONTINUE_PROP);
      assertEquals(52, Node.LENGTH);
      assertEquals(44, Node.IS_OPTIONAL_PARAM);
      assertEquals(0, Node.SIDE_EFFECTS_ALL);
      assertEquals(2, Node.BREAK_PROP);
      assertEquals((-1), Node.CATCH_SCOPE_PROP);
      assertEquals(2, Node.ATTRIBUTE_FLAG);
      assertEquals(2, Node.FLAG_THIS_UNMODIFIED);
      assertEquals(1, Node.DECR_FLAG);
      assertEquals(30, Node.VAR_ARGS_NAME);
      assertEquals(11, Node.USES_PROP);
      assertEquals(47, Node.IS_DISPATCHER);
      assertEquals(12, Node.COLUMN_BITS);
      assertEquals(7, Node.LOCAL_PROP);
      assertEquals(34, Node.NAME_PROP);
      assertEquals(6, Node.TEMP_PROP);
      assertEquals(1, Node.SPECIALCALL_EVAL);
      assertEquals(41, Node.BRACELESS_TYPE);
      assertEquals(12, Node.REGEXP_PROP);
      assertEquals(51, Node.STATIC_SOURCE_FILE);
      assertEquals(5, Node.FUNCTION_PROP);
      assertEquals(27, Node.SPECIALCALL_PROP);
      assertEquals(8, Node.FLAG_NO_THROWS);
      assertEquals(23, Node.VARIABLE_PROP);
      assertEquals(13, Node.CASES_PROP);
      assertEquals(2, Node.SPECIALCALL_WITH);
      assertEquals(21, Node.LOCALCOUNT_PROP);
      assertEquals(1, Node.FLAG_GLOBAL_STATE_UNMODIFIED);
      assertEquals(45, Node.IS_VAR_ARGS_PARAM);
      assertEquals(1, Node.PROPERTY_FLAG);
      assertEquals(42, Node.SIDE_EFFECT_FLAGS);
      assertEquals(31, Node.SKIP_INDEXES_PROP);
      assertEquals(9, Node.FIXUPS_PROP);
      assertEquals(28, Node.DEBUGSOURCE_PROP);
      assertEquals(14, Node.DEFAULT_PROP);
      assertEquals(53, Node.INPUT_ID);
      assertEquals(36, Node.QUOTED_PROP);
      assertEquals(15, Node.NO_SIDE_EFFECTS);
      assertEquals(19, Node.LABEL_PROP);
      assertEquals(22, Node.TARGETBLOCK_PROP);
      assertEquals(10, Node.VARS_PROP);
      assertEquals(18, Node.SPECIAL_PROP_PROP);
      assertEquals(49, Node.DIRECT_EVAL);
      assertEquals(4, Node.DESCENDANTS_FLAG);
      assertEquals((-3), Node.LOCAL_BLOCK_PROP);
      assertEquals(0, Node.NON_SPECIALCALL);
      assertEquals(16, Node.FLAG_LOCAL_RESULTS);
      assertEquals(2, Node.POST_FLAG);
      assertEquals(4, Node.FLAG_ARGUMENTS_UNMODIFIED);
      assertEquals(37, Node.OPT_ARG_NAME);
      assertEquals(33, Node.MEMBER_TYPE_PROP);
      assertEquals(0, Node.BOTH);
      assertEquals(29, Node.JSDOC_INFO_PROP);
      assertEquals(1, Node.LEFT);
      assertEquals(2, Node.RIGHT);
      assertEquals(32, Node.INCRDECR_PROP);
      assertEquals(53, Node.LAST_PROP);
      assertEquals(25, Node.ISNUMBER_PROP);
      assertEquals(0, Node.LABEL_ID_PROP);
      assertEquals(40, Node.ORIGINALNAME_PROP);
      assertEquals(8, Node.CODEOFFSET_PROP);
      assertEquals(50, Node.FREE_CALL);
      assertEquals(1, Node.TARGET_PROP);
      assertEquals(46, Node.IS_NAMESPACE);
      assertEquals(16, Node.SOURCENAME_PROP);
      assertEquals(43, Node.IS_CONSTANT_NAME);
      assertEquals(3108, node0.getType());
      assertFalse(node0.wasEmptyNode());
      assertFalse(node0.hasMoreThanOneChild());
      assertEquals((-1), node0.getCharno());
      assertEquals(0, node0.getSideEffectFlags());
      assertEquals(0, node0.getChildCount());
      assertEquals((-1), node0.getLineno());
      assertFalse(node0.isQualifiedName());
      assertFalse(node0.isSyntheticBlock());
      assertFalse(node0.isLocalResultCall());
      assertEquals(0, node0.getLength());
      assertEquals(Integer.MAX_VALUE, node0.getSourceOffset());
      assertFalse(node0.hasChildren());
      assertFalse(node0.isOptionalArg());
      assertFalse(node0.isVarArgs());
      assertEquals((-1), node0.getSourcePosition());
      assertFalse(node0.isNoSideEffectsCall());
      assertNull(node0.getSourceFileName());
      assertFalse(node0.isOnlyModifiesThisCall());
      assertFalse(node0.isUnscopedQualifiedName());
      assertFalse(node0.isFromExterns());
      assertFalse(node0.isQuotedString());
      assertFalse(node0.hasOneChild());
      assertNotNull(node0);
      
      CodeGenerator.Context codeGenerator_Context0 = CodeGenerator.Context.START_OF_EXPR;
      // Undeclared exception!
      try { 
        codeGenerator0.addList(node0, false, codeGenerator_Context0);
        fail("Expecting exception: Error");
      
      } catch(Error e) {
         //
         // Unknown precedence for <unknown=3108> (type 3108)
         //
         verifyException("com.google.javascript.jscomp.NodeUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CodeGenerator codeGenerator0 = new CodeGenerator((CodeConsumer) null);
      assertNotNull(codeGenerator0);
      
      CodeGenerator.Context codeGenerator_Context0 = CodeGenerator.Context.IN_FOR_INIT_CLAUSE;
      Node node0 = Node.newString(",a-", 75, 75);
      assertEquals(1, Node.TARGET_PROP);
      assertEquals(27, Node.SPECIALCALL_PROP);
      assertEquals(12, Node.COLUMN_BITS);
      assertEquals((-1), Node.CATCH_SCOPE_PROP);
      assertEquals(4, Node.FLAG_ARGUMENTS_UNMODIFIED);
      assertEquals(37, Node.OPT_ARG_NAME);
      assertEquals(0, Node.BOTH);
      assertEquals(0, Node.NON_SPECIALCALL);
      assertEquals(29, Node.JSDOC_INFO_PROP);
      assertEquals(2, Node.FLAG_THIS_UNMODIFIED);
      assertEquals(51, Node.STATIC_SOURCE_FILE);
      assertEquals(52, Node.LENGTH);
      assertEquals(53, Node.INPUT_ID);
      assertEquals(47, Node.IS_DISPATCHER);
      assertEquals(24, Node.LASTUSE_PROP);
      assertEquals(53, Node.LAST_PROP);
      assertEquals(30, Node.VAR_ARGS_NAME);
      assertEquals(11, Node.USES_PROP);
      assertEquals(6, Node.TEMP_PROP);
      assertEquals(15, Node.CASEARRAY_PROP);
      assertEquals(1, Node.FLAG_GLOBAL_STATE_UNMODIFIED);
      assertEquals(48, Node.DIRECTIVES);
      assertEquals(17, Node.TYPE_PROP);
      assertEquals(5, Node.FUNCTION_PROP);
      assertEquals(4095, Node.MAX_COLUMN_NUMBER);
      assertEquals(20, Node.FINALLY_PROP);
      assertEquals(16, Node.FLAG_LOCAL_RESULTS);
      assertEquals(7, Node.LOCAL_PROP);
      assertEquals(41, Node.BRACELESS_TYPE);
      assertEquals(1, Node.SPECIALCALL_EVAL);
      assertEquals(19, Node.LABEL_PROP);
      assertEquals(4, Node.DESCENDANTS_FLAG);
      assertEquals(10, Node.VARS_PROP);
      assertEquals(12, Node.REGEXP_PROP);
      assertEquals(44, Node.IS_OPTIONAL_PARAM);
      assertEquals(0, Node.SIDE_EFFECTS_ALL);
      assertEquals(18, Node.SPECIAL_PROP_PROP);
      assertEquals(21, Node.LOCALCOUNT_PROP);
      assertEquals(34, Node.NAME_PROP);
      assertEquals(13, Node.CASES_PROP);
      assertEquals(31, Node.SKIP_INDEXES_PROP);
      assertEquals(28, Node.DEBUGSOURCE_PROP);
      assertEquals(14, Node.DEFAULT_PROP);
      assertEquals(46, Node.IS_NAMESPACE);
      assertEquals(32, Node.INCRDECR_PROP);
      assertEquals(2, Node.ATTRIBUTE_FLAG);
      assertEquals(1, Node.DECR_FLAG);
      assertEquals(49, Node.DIRECT_EVAL);
      assertEquals(15, Node.NO_SIDE_EFFECTS);
      assertEquals(33, Node.MEMBER_TYPE_PROP);
      assertEquals(22, Node.TARGETBLOCK_PROP);
      assertEquals(2, Node.BREAK_PROP);
      assertEquals(35, Node.PARENTHESIZED_PROP);
      assertEquals(40, Node.ORIGINALNAME_PROP);
      assertEquals(0, Node.LABEL_ID_PROP);
      assertEquals(42, Node.SIDE_EFFECT_FLAGS);
      assertEquals(2, Node.POST_FLAG);
      assertEquals(4095, Node.COLUMN_MASK);
      assertEquals(2, Node.SPECIALCALL_WITH);
      assertEquals(39, Node.EMPTY_BLOCK);
      assertEquals(4, Node.ENUM_PROP);
      assertEquals((-3), Node.LOCAL_BLOCK_PROP);
      assertEquals(16, Node.SOURCENAME_PROP);
      assertEquals(3, Node.CONTINUE_PROP);
      assertEquals(26, Node.DIRECTCALL_PROP);
      assertEquals(43, Node.IS_CONSTANT_NAME);
      assertEquals(8, Node.FLAG_NO_THROWS);
      assertEquals(8, Node.CODEOFFSET_PROP);
      assertEquals(50, Node.FREE_CALL);
      assertEquals(36, Node.QUOTED_PROP);
      assertEquals(25, Node.ISNUMBER_PROP);
      assertEquals(31, Node.SIDE_EFFECTS_FLAGS_MASK);
      assertEquals((-2), Node.OBJECT_IDS_PROP);
      assertEquals(45, Node.IS_VAR_ARGS_PARAM);
      assertEquals(1, Node.PROPERTY_FLAG);
      assertEquals(9, Node.FIXUPS_PROP);
      assertEquals(38, Node.SYNTHETIC_BLOCK_PROP);
      assertEquals(1, Node.LEFT);
      assertEquals(2, Node.RIGHT);
      assertEquals(23, Node.VARIABLE_PROP);
      assertFalse(node0.isLocalResultCall());
      assertEquals((-2147483573), node0.getSourceOffset());
      assertFalse(node0.isUnscopedQualifiedName());
      assertEquals(75, node0.getLineno());
      assertFalse(node0.hasMoreThanOneChild());
      assertFalse(node0.isQuotedString());
      assertFalse(node0.hasOneChild());
      assertFalse(node0.isNoSideEffectsCall());
      assertEquals(0, node0.getSideEffectFlags());
      assertEquals(0, node0.getChildCount());
      assertFalse(node0.hasChildren());
      assertFalse(node0.wasEmptyNode());
      assertFalse(node0.isOnlyModifiesThisCall());
      assertEquals(40, node0.getType());
      assertFalse(node0.isOptionalArg());
      assertFalse(node0.isFromExterns());
      assertFalse(node0.isVarArgs());
      assertEquals(75, node0.getCharno());
      assertEquals(307275, node0.getSourcePosition());
      assertEquals(0, node0.getLength());
      assertNull(node0.getSourceFileName());
      assertFalse(node0.isQualifiedName());
      assertFalse(node0.isSyntheticBlock());
      assertNotNull(node0);
      
      // Undeclared exception!
      try { 
        codeGenerator0.addLeftExpr(node0, 0, codeGenerator_Context0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.javascript.jscomp.CodeGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CodeGenerator codeGenerator0 = new CodeGenerator((CodeConsumer) null);
      assertNotNull(codeGenerator0);
      
      Node node0 = Node.newString("beO;H 8Q", 75, 75);
      assertEquals(1, Node.DECR_FLAG);
      assertEquals(49, Node.DIRECT_EVAL);
      assertEquals(46, Node.IS_NAMESPACE);
      assertEquals(4, Node.DESCENDANTS_FLAG);
      assertEquals(0, Node.LABEL_ID_PROP);
      assertEquals(10, Node.VARS_PROP);
      assertEquals(18, Node.SPECIAL_PROP_PROP);
      assertEquals(40, Node.ORIGINALNAME_PROP);
      assertEquals(31, Node.SKIP_INDEXES_PROP);
      assertEquals(21, Node.LOCALCOUNT_PROP);
      assertEquals(50, Node.FREE_CALL);
      assertEquals(8, Node.CODEOFFSET_PROP);
      assertEquals(23, Node.VARIABLE_PROP);
      assertEquals(25, Node.ISNUMBER_PROP);
      assertEquals(41, Node.BRACELESS_TYPE);
      assertEquals(32, Node.INCRDECR_PROP);
      assertEquals(2, Node.SPECIALCALL_WITH);
      assertEquals(34, Node.NAME_PROP);
      assertEquals(45, Node.IS_VAR_ARGS_PARAM);
      assertEquals(3, Node.CONTINUE_PROP);
      assertEquals(1, Node.PROPERTY_FLAG);
      assertEquals(36, Node.QUOTED_PROP);
      assertEquals(5, Node.FUNCTION_PROP);
      assertEquals(9, Node.FIXUPS_PROP);
      assertEquals(7, Node.LOCAL_PROP);
      assertEquals((-2), Node.OBJECT_IDS_PROP);
      assertEquals(6, Node.TEMP_PROP);
      assertEquals(4095, Node.COLUMN_MASK);
      assertEquals(31, Node.SIDE_EFFECTS_FLAGS_MASK);
      assertEquals(0, Node.NON_SPECIALCALL);
      assertEquals(2, Node.BREAK_PROP);
      assertEquals((-3), Node.LOCAL_BLOCK_PROP);
      assertEquals(11, Node.USES_PROP);
      assertEquals(47, Node.IS_DISPATCHER);
      assertEquals(52, Node.LENGTH);
      assertEquals(2, Node.ATTRIBUTE_FLAG);
      assertEquals(39, Node.EMPTY_BLOCK);
      assertEquals(8, Node.FLAG_NO_THROWS);
      assertEquals(53, Node.INPUT_ID);
      assertEquals(30, Node.VAR_ARGS_NAME);
      assertEquals(1, Node.LEFT);
      assertEquals(51, Node.STATIC_SOURCE_FILE);
      assertEquals(53, Node.LAST_PROP);
      assertEquals(38, Node.SYNTHETIC_BLOCK_PROP);
      assertEquals(12, Node.COLUMN_BITS);
      assertEquals(1, Node.TARGET_PROP);
      assertEquals(27, Node.SPECIALCALL_PROP);
      assertEquals(37, Node.OPT_ARG_NAME);
      assertEquals(26, Node.DIRECTCALL_PROP);
      assertEquals(2, Node.FLAG_THIS_UNMODIFIED);
      assertEquals(2, Node.RIGHT);
      assertEquals((-1), Node.CATCH_SCOPE_PROP);
      assertEquals(12, Node.REGEXP_PROP);
      assertEquals(1, Node.SPECIALCALL_EVAL);
      assertEquals(4, Node.FLAG_ARGUMENTS_UNMODIFIED);
      assertEquals(20, Node.FINALLY_PROP);
      assertEquals(16, Node.FLAG_LOCAL_RESULTS);
      assertEquals(43, Node.IS_CONSTANT_NAME);
      assertEquals(15, Node.CASEARRAY_PROP);
      assertEquals(16, Node.SOURCENAME_PROP);
      assertEquals(19, Node.LABEL_PROP);
      assertEquals(14, Node.DEFAULT_PROP);
      assertEquals(48, Node.DIRECTIVES);
      assertEquals(28, Node.DEBUGSOURCE_PROP);
      assertEquals(44, Node.IS_OPTIONAL_PARAM);
      assertEquals(0, Node.SIDE_EFFECTS_ALL);
      assertEquals(13, Node.CASES_PROP);
      assertEquals(4, Node.ENUM_PROP);
      assertEquals(4095, Node.MAX_COLUMN_NUMBER);
      assertEquals(24, Node.LASTUSE_PROP);
      assertEquals(0, Node.BOTH);
      assertEquals(2, Node.POST_FLAG);
      assertEquals(42, Node.SIDE_EFFECT_FLAGS);
      assertEquals(17, Node.TYPE_PROP);
      assertEquals(35, Node.PARENTHESIZED_PROP);
      assertEquals(15, Node.NO_SIDE_EFFECTS);
      assertEquals(33, Node.MEMBER_TYPE_PROP);
      assertEquals(29, Node.JSDOC_INFO_PROP);
      assertEquals(1, Node.FLAG_GLOBAL_STATE_UNMODIFIED);
      assertEquals(22, Node.TARGETBLOCK_PROP);
      assertFalse(node0.hasOneChild());
      assertEquals(0, node0.getLength());
      assertNull(node0.getSourceFileName());
      assertFalse(node0.isQuotedString());
      assertFalse(node0.isOptionalArg());
      assertEquals(75, node0.getLineno());
      assertEquals((-2147483573), node0.getSourceOffset());
      assertFalse(node0.isFromExterns());
      assertFalse(node0.isUnscopedQualifiedName());
      assertEquals(307275, node0.getSourcePosition());
      assertEquals(0, node0.getSideEffectFlags());
      assertEquals(0, node0.getChildCount());
      assertFalse(node0.isSyntheticBlock());
      assertFalse(node0.isQualifiedName());
      assertFalse(node0.isOnlyModifiesThisCall());
      assertEquals(40, node0.getType());
      assertFalse(node0.isLocalResultCall());
      assertFalse(node0.hasChildren());
      assertFalse(node0.wasEmptyNode());
      assertFalse(node0.isNoSideEffectsCall());
      assertEquals(75, node0.getCharno());
      assertFalse(node0.hasMoreThanOneChild());
      assertFalse(node0.isVarArgs());
      assertNotNull(node0);
      
      CodeGenerator.Context codeGenerator_Context0 = CodeGenerator.Context.IN_FOR_INIT_CLAUSE;
      // Undeclared exception!
      try { 
        codeGenerator0.addLeftExpr(node0, 48, codeGenerator_Context0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.javascript.jscomp.CodeGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      double double0 = CodeGenerator.getSimpleNumber("");
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      double double0 = CodeGenerator.getSimpleNumber("8[2D0FP8/E#+gNI5");
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      double double0 = CodeGenerator.getSimpleNumber("!--");
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      double double0 = CodeGenerator.getSimpleNumber("6");
      assertEquals(6.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Charset charset0 = Charset.defaultCharset();
      assertEquals("UTF-8", charset0.toString());
      assertTrue(charset0.isRegistered());
      assertTrue(charset0.canEncode());
      assertEquals("UTF-8", charset0.name());
      assertEquals("UTF-8", charset0.displayName());
      assertNotNull(charset0);
      
      CodeGenerator codeGenerator0 = new CodeGenerator((CodeConsumer) null, charset0);
      assertEquals("UTF-8", charset0.toString());
      assertTrue(charset0.isRegistered());
      assertTrue(charset0.canEncode());
      assertEquals("UTF-8", charset0.name());
      assertEquals("UTF-8", charset0.displayName());
      assertNotNull(codeGenerator0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      CodeGenerator codeGenerator0 = new CodeGenerator((CodeConsumer) null);
      assertNotNull(codeGenerator0);
      
      codeGenerator0.addList((Node) null, false);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Node node0 = Node.newNumber(Double.POSITIVE_INFINITY);
      assertEquals(53, Node.LAST_PROP);
      assertEquals(38, Node.SYNTHETIC_BLOCK_PROP);
      assertEquals(51, Node.STATIC_SOURCE_FILE);
      assertEquals(1, Node.SPECIALCALL_EVAL);
      assertEquals(52, Node.LENGTH);
      assertEquals((-1), Node.CATCH_SCOPE_PROP);
      assertEquals(4095, Node.MAX_COLUMN_NUMBER);
      assertEquals(20, Node.FINALLY_PROP);
      assertEquals(26, Node.DIRECTCALL_PROP);
      assertEquals(37, Node.OPT_ARG_NAME);
      assertEquals(0, Node.BOTH);
      assertEquals(4, Node.FLAG_ARGUMENTS_UNMODIFIED);
      assertEquals(48, Node.DIRECTIVES);
      assertEquals(15, Node.CASEARRAY_PROP);
      assertEquals(12, Node.COLUMN_BITS);
      assertEquals(0, Node.NON_SPECIALCALL);
      assertEquals(2, Node.RIGHT);
      assertEquals(1, Node.LEFT);
      assertEquals(31, Node.SIDE_EFFECTS_FLAGS_MASK);
      assertEquals(19, Node.LABEL_PROP);
      assertEquals(4095, Node.COLUMN_MASK);
      assertEquals(16, Node.FLAG_LOCAL_RESULTS);
      assertEquals(35, Node.PARENTHESIZED_PROP);
      assertEquals(25, Node.ISNUMBER_PROP);
      assertEquals(16, Node.SOURCENAME_PROP);
      assertEquals((-2), Node.OBJECT_IDS_PROP);
      assertEquals(45, Node.IS_VAR_ARGS_PARAM);
      assertEquals(1, Node.PROPERTY_FLAG);
      assertEquals(9, Node.FIXUPS_PROP);
      assertEquals(43, Node.IS_CONSTANT_NAME);
      assertEquals(1, Node.FLAG_GLOBAL_STATE_UNMODIFIED);
      assertEquals(17, Node.TYPE_PROP);
      assertEquals(29, Node.JSDOC_INFO_PROP);
      assertEquals(2, Node.SPECIALCALL_WITH);
      assertEquals(33, Node.MEMBER_TYPE_PROP);
      assertEquals(4, Node.ENUM_PROP);
      assertEquals(2, Node.POST_FLAG);
      assertEquals(46, Node.IS_NAMESPACE);
      assertEquals(42, Node.SIDE_EFFECT_FLAGS);
      assertEquals(40, Node.ORIGINALNAME_PROP);
      assertEquals(1, Node.TARGET_PROP);
      assertEquals(24, Node.LASTUSE_PROP);
      assertEquals(0, Node.LABEL_ID_PROP);
      assertEquals(21, Node.LOCALCOUNT_PROP);
      assertEquals(8, Node.CODEOFFSET_PROP);
      assertEquals(50, Node.FREE_CALL);
      assertEquals(41, Node.BRACELESS_TYPE);
      assertEquals(1, Node.DECR_FLAG);
      assertEquals(2, Node.ATTRIBUTE_FLAG);
      assertEquals(22, Node.TARGETBLOCK_PROP);
      assertEquals(15, Node.NO_SIDE_EFFECTS);
      assertEquals(8, Node.FLAG_NO_THROWS);
      assertEquals(23, Node.VARIABLE_PROP);
      assertEquals(31, Node.SKIP_INDEXES_PROP);
      assertEquals((-3), Node.LOCAL_BLOCK_PROP);
      assertEquals(32, Node.INCRDECR_PROP);
      assertEquals(18, Node.SPECIAL_PROP_PROP);
      assertEquals(10, Node.VARS_PROP);
      assertEquals(4, Node.DESCENDANTS_FLAG);
      assertEquals(49, Node.DIRECT_EVAL);
      assertEquals(0, Node.SIDE_EFFECTS_ALL);
      assertEquals(44, Node.IS_OPTIONAL_PARAM);
      assertEquals(13, Node.CASES_PROP);
      assertEquals(7, Node.LOCAL_PROP);
      assertEquals(28, Node.DEBUGSOURCE_PROP);
      assertEquals(14, Node.DEFAULT_PROP);
      assertEquals(36, Node.QUOTED_PROP);
      assertEquals(6, Node.TEMP_PROP);
      assertEquals(5, Node.FUNCTION_PROP);
      assertEquals(12, Node.REGEXP_PROP);
      assertEquals(3, Node.CONTINUE_PROP);
      assertEquals(2, Node.BREAK_PROP);
      assertEquals(34, Node.NAME_PROP);
      assertEquals(53, Node.INPUT_ID);
      assertEquals(2, Node.FLAG_THIS_UNMODIFIED);
      assertEquals(39, Node.EMPTY_BLOCK);
      assertEquals(47, Node.IS_DISPATCHER);
      assertEquals(11, Node.USES_PROP);
      assertEquals(30, Node.VAR_ARGS_NAME);
      assertEquals(27, Node.SPECIALCALL_PROP);
      assertEquals(Integer.MAX_VALUE, node0.getSourceOffset());
      assertFalse(node0.isOptionalArg());
      assertFalse(node0.hasChildren());
      assertFalse(node0.isFromExterns());
      assertFalse(node0.isQuotedString());
      assertFalse(node0.hasOneChild());
      assertEquals(0, node0.getLength());
      assertFalse(node0.isOnlyModifiesThisCall());
      assertEquals((-1), node0.getLineno());
      assertFalse(node0.hasMoreThanOneChild());
      assertFalse(node0.isVarArgs());
      assertEquals(0, node0.getChildCount());
      assertFalse(node0.isNoSideEffectsCall());
      assertEquals(0, node0.getSideEffectFlags());
      assertEquals(39, node0.getType());
      assertFalse(node0.wasEmptyNode());
      assertFalse(node0.isLocalResultCall());
      assertFalse(node0.isUnscopedQualifiedName());
      assertFalse(node0.isQualifiedName());
      assertFalse(node0.isSyntheticBlock());
      assertEquals((-1), node0.getCharno());
      assertEquals((-1), node0.getSourcePosition());
      assertNull(node0.getSourceFileName());
      assertNotNull(node0);
      
      CodeGenerator codeGenerator0 = new CodeGenerator((CodeConsumer) null);
      assertNotNull(codeGenerator0);
      
      // Undeclared exception!
      try { 
        codeGenerator0.addAllSiblings(node0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.javascript.jscomp.CodeGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      CodeGenerator codeGenerator0 = new CodeGenerator((CodeConsumer) null);
      assertNotNull(codeGenerator0);
      
      // Undeclared exception!
      try { 
        codeGenerator0.addCaseBody((Node) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.javascript.jscomp.CodeGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      CodeGenerator codeGenerator0 = new CodeGenerator((CodeConsumer) null);
      assertNotNull(codeGenerator0);
      
      // Undeclared exception!
      try { 
        codeGenerator0.tagAsStrict();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.javascript.jscomp.CodeGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Node node0 = Node.newNumber(0.0);
      assertEquals(39, Node.EMPTY_BLOCK);
      assertEquals(31, Node.SIDE_EFFECTS_FLAGS_MASK);
      assertEquals(4, Node.ENUM_PROP);
      assertEquals(20, Node.FINALLY_PROP);
      assertEquals(48, Node.DIRECTIVES);
      assertEquals(4095, Node.COLUMN_MASK);
      assertEquals(15, Node.CASEARRAY_PROP);
      assertEquals(24, Node.LASTUSE_PROP);
      assertEquals(35, Node.PARENTHESIZED_PROP);
      assertEquals(53, Node.LAST_PROP);
      assertEquals(17, Node.TYPE_PROP);
      assertEquals(4095, Node.MAX_COLUMN_NUMBER);
      assertEquals(52, Node.LENGTH);
      assertEquals(2, Node.BREAK_PROP);
      assertEquals(3, Node.CONTINUE_PROP);
      assertEquals(47, Node.IS_DISPATCHER);
      assertEquals(27, Node.SPECIALCALL_PROP);
      assertEquals(44, Node.IS_OPTIONAL_PARAM);
      assertEquals(11, Node.USES_PROP);
      assertEquals(0, Node.SIDE_EFFECTS_ALL);
      assertEquals(12, Node.COLUMN_BITS);
      assertEquals(30, Node.VAR_ARGS_NAME);
      assertEquals(19, Node.LABEL_PROP);
      assertEquals(6, Node.TEMP_PROP);
      assertEquals(14, Node.DEFAULT_PROP);
      assertEquals(28, Node.DEBUGSOURCE_PROP);
      assertEquals(5, Node.FUNCTION_PROP);
      assertEquals(7, Node.LOCAL_PROP);
      assertEquals(34, Node.NAME_PROP);
      assertEquals(1, Node.DECR_FLAG);
      assertEquals(51, Node.STATIC_SOURCE_FILE);
      assertEquals((-1), Node.CATCH_SCOPE_PROP);
      assertEquals(12, Node.REGEXP_PROP);
      assertEquals(2, Node.FLAG_THIS_UNMODIFIED);
      assertEquals(1, Node.SPECIALCALL_EVAL);
      assertEquals(41, Node.BRACELESS_TYPE);
      assertEquals(42, Node.SIDE_EFFECT_FLAGS);
      assertEquals(8, Node.FLAG_NO_THROWS);
      assertEquals(23, Node.VARIABLE_PROP);
      assertEquals(13, Node.CASES_PROP);
      assertEquals(31, Node.SKIP_INDEXES_PROP);
      assertEquals(21, Node.LOCALCOUNT_PROP);
      assertEquals((-3), Node.LOCAL_BLOCK_PROP);
      assertEquals(10, Node.VARS_PROP);
      assertEquals(18, Node.SPECIAL_PROP_PROP);
      assertEquals(40, Node.ORIGINALNAME_PROP);
      assertEquals(16, Node.FLAG_LOCAL_RESULTS);
      assertEquals(36, Node.QUOTED_PROP);
      assertEquals(15, Node.NO_SIDE_EFFECTS);
      assertEquals(22, Node.TARGETBLOCK_PROP);
      assertEquals(53, Node.INPUT_ID);
      assertEquals(4, Node.DESCENDANTS_FLAG);
      assertEquals(49, Node.DIRECT_EVAL);
      assertEquals(29, Node.JSDOC_INFO_PROP);
      assertEquals(1, Node.FLAG_GLOBAL_STATE_UNMODIFIED);
      assertEquals(2, Node.ATTRIBUTE_FLAG);
      assertEquals(0, Node.BOTH);
      assertEquals(2, Node.POST_FLAG);
      assertEquals(4, Node.FLAG_ARGUMENTS_UNMODIFIED);
      assertEquals(37, Node.OPT_ARG_NAME);
      assertEquals(33, Node.MEMBER_TYPE_PROP);
      assertEquals(0, Node.NON_SPECIALCALL);
      assertEquals(1, Node.TARGET_PROP);
      assertEquals(32, Node.INCRDECR_PROP);
      assertEquals(2, Node.RIGHT);
      assertEquals(1, Node.LEFT);
      assertEquals(1, Node.PROPERTY_FLAG);
      assertEquals(43, Node.IS_CONSTANT_NAME);
      assertEquals(38, Node.SYNTHETIC_BLOCK_PROP);
      assertEquals(9, Node.FIXUPS_PROP);
      assertEquals(16, Node.SOURCENAME_PROP);
      assertEquals((-2), Node.OBJECT_IDS_PROP);
      assertEquals(45, Node.IS_VAR_ARGS_PARAM);
      assertEquals(25, Node.ISNUMBER_PROP);
      assertEquals(0, Node.LABEL_ID_PROP);
      assertEquals(8, Node.CODEOFFSET_PROP);
      assertEquals(2, Node.SPECIALCALL_WITH);
      assertEquals(46, Node.IS_NAMESPACE);
      assertEquals(26, Node.DIRECTCALL_PROP);
      assertEquals(50, Node.FREE_CALL);
      assertFalse(node0.hasMoreThanOneChild());
      assertFalse(node0.isLocalResultCall());
      assertEquals((-1), node0.getLineno());
      assertFalse(node0.isUnscopedQualifiedName());
      assertEquals((-1), node0.getSourcePosition());
      assertNull(node0.getSourceFileName());
      assertFalse(node0.isSyntheticBlock());
      assertFalse(node0.isQualifiedName());
      assertEquals((-1), node0.getCharno());
      assertFalse(node0.isOptionalArg());
      assertFalse(node0.isNoSideEffectsCall());
      assertFalse(node0.hasOneChild());
      assertEquals(0, node0.getLength());
      assertFalse(node0.isFromExterns());
      assertFalse(node0.isQuotedString());
      assertEquals(Integer.MAX_VALUE, node0.getSourceOffset());
      assertFalse(node0.isVarArgs());
      assertEquals(0, node0.getSideEffectFlags());
      assertEquals(0, node0.getChildCount());
      assertEquals(39, node0.getType());
      assertFalse(node0.hasChildren());
      assertFalse(node0.wasEmptyNode());
      assertFalse(node0.isOnlyModifiesThisCall());
      assertNotNull(node0);
      
      CodeGenerator codeGenerator0 = new CodeGenerator((CodeConsumer) null);
      assertNotNull(codeGenerator0);
      
      // Undeclared exception!
      try { 
        codeGenerator0.addList(node0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.javascript.jscomp.CodeGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      CodeGenerator codeGenerator0 = new CodeGenerator((CodeConsumer) null);
      assertNotNull(codeGenerator0);
      
      // Undeclared exception!
      try { 
        codeGenerator0.addJsString("#g\";O|%");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.javascript.jscomp.CodeGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      String string0 = CodeGenerator.regexpEscape("+Y;.+dBCGBj]]>^]d");
      assertEquals("/+Y;.+dBCGBj]]\\>^]d/", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      CodeGenerator codeGenerator0 = new CodeGenerator((CodeConsumer) null);
      assertNotNull(codeGenerator0);
      
      // Undeclared exception!
      try { 
        codeGenerator0.addJsString("u`5-h'>%AlFq\"M7CI`s");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.javascript.jscomp.CodeGenerator", e);
      }
  }
}
