/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 05 03:50:55 GMT 2026
 */

package org.joda.time.chrono;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.TimeZone;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.joda.time.Chronology;
import org.joda.time.DateTimeZone;
import org.joda.time.LocalDateTime;
import org.joda.time.MonthDay;
import org.joda.time.Partial;
import org.joda.time.ReadablePartial;
import org.joda.time.chrono.BasicMonthOfYearDateTimeField;
import org.joda.time.chrono.CopticChronology;
import org.joda.time.chrono.EthiopicChronology;
import org.joda.time.chrono.GJMonthOfYearDateTimeField;
import org.joda.time.chrono.GregorianChronology;
import org.joda.time.chrono.JulianChronology;
import org.joda.time.tz.FixedDateTimeZone;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class BasicMonthOfYearDateTimeField_ESTest extends BasicMonthOfYearDateTimeField_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      EthiopicChronology ethiopicChronology0 = EthiopicChronology.getInstance();
      assertNotNull(ethiopicChronology0);
      assertEquals(1, EthiopicChronology.EE);
      
      GJMonthOfYearDateTimeField gJMonthOfYearDateTimeField0 = new GJMonthOfYearDateTimeField(ethiopicChronology0);
      assertNotNull(gJMonthOfYearDateTimeField0);
      assertEquals(1, EthiopicChronology.EE);
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertEquals(13, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      
      int int0 = gJMonthOfYearDateTimeField0.getLeapAmount((-12219292800000L));
      assertEquals(1, EthiopicChronology.EE);
      assertEquals(1, int0);
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertEquals(13, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      EthiopicChronology ethiopicChronology0 = EthiopicChronology.getInstance();
      assertNotNull(ethiopicChronology0);
      assertEquals(1, EthiopicChronology.EE);
      
      GJMonthOfYearDateTimeField gJMonthOfYearDateTimeField0 = new GJMonthOfYearDateTimeField(ethiopicChronology0);
      assertNotNull(gJMonthOfYearDateTimeField0);
      assertEquals(1, EthiopicChronology.EE);
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      assertEquals(13, gJMonthOfYearDateTimeField0.getMaximumValue());
      
      int int0 = gJMonthOfYearDateTimeField0.getLeapAmount(1291248000001L);
      assertEquals(1, EthiopicChronology.EE);
      assertEquals(0, int0);
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      assertEquals(13, gJMonthOfYearDateTimeField0.getMaximumValue());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      EthiopicChronology ethiopicChronology0 = EthiopicChronology.getInstance();
      assertNotNull(ethiopicChronology0);
      assertEquals(1, EthiopicChronology.EE);
      
      GJMonthOfYearDateTimeField gJMonthOfYearDateTimeField0 = new GJMonthOfYearDateTimeField(ethiopicChronology0);
      assertNotNull(gJMonthOfYearDateTimeField0);
      assertEquals(1, EthiopicChronology.EE);
      assertEquals(13, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      
      boolean boolean0 = gJMonthOfYearDateTimeField0.isLeap(1);
      assertEquals(1, EthiopicChronology.EE);
      assertFalse(boolean0);
      assertEquals(13, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      GregorianChronology gregorianChronology0 = GregorianChronology.getInstance();
      assertNotNull(gregorianChronology0);
      
      MonthDay monthDay0 = MonthDay.now((Chronology) gregorianChronology0);
      assertNotNull(monthDay0);
      assertEquals(1, MonthDay.DAY_OF_MONTH);
      assertEquals(0, MonthDay.MONTH_OF_YEAR);
      assertEquals(2, monthDay0.getMonthOfYear());
      assertEquals(14, monthDay0.getDayOfMonth());
      assertEquals(2, monthDay0.size());
      
      long long0 = gregorianChronology0.set(monthDay0, 78L);
      assertEquals(1, MonthDay.DAY_OF_MONTH);
      assertEquals(0, MonthDay.MONTH_OF_YEAR);
      assertEquals((-27647999922L), long0);
      assertEquals(2, monthDay0.getMonthOfYear());
      assertEquals(14, monthDay0.getDayOfMonth());
      assertEquals(2, monthDay0.size());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      GregorianChronology gregorianChronology0 = GregorianChronology.getInstance();
      assertNotNull(gregorianChronology0);
      
      GJMonthOfYearDateTimeField gJMonthOfYearDateTimeField0 = new GJMonthOfYearDateTimeField(gregorianChronology0);
      assertNotNull(gJMonthOfYearDateTimeField0);
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertEquals(12, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      
      long long0 = gJMonthOfYearDateTimeField0.getDifferenceAsLong(7043509766505598629L, (-1261L));
      assertEquals(2678399269L, long0);
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertEquals(12, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      EthiopicChronology ethiopicChronology0 = EthiopicChronology.getInstance();
      assertNotNull(ethiopicChronology0);
      assertEquals(1, EthiopicChronology.EE);
      
      BasicMonthOfYearDateTimeField basicMonthOfYearDateTimeField0 = new BasicMonthOfYearDateTimeField(ethiopicChronology0, 2108);
      assertNotNull(basicMonthOfYearDateTimeField0);
      assertEquals(1, EthiopicChronology.EE);
      assertEquals(1, basicMonthOfYearDateTimeField0.getMinimumValue());
      assertTrue(basicMonthOfYearDateTimeField0.isSupported());
      assertEquals("monthOfYear", basicMonthOfYearDateTimeField0.getName());
      assertFalse(basicMonthOfYearDateTimeField0.isLenient());
      assertEquals(13, basicMonthOfYearDateTimeField0.getMaximumValue());
      
      long long0 = basicMonthOfYearDateTimeField0.getDifferenceAsLong(1, 2108);
      assertEquals(1, EthiopicChronology.EE);
      assertEquals(0L, long0);
      assertEquals(1, basicMonthOfYearDateTimeField0.getMinimumValue());
      assertTrue(basicMonthOfYearDateTimeField0.isSupported());
      assertEquals("monthOfYear", basicMonthOfYearDateTimeField0.getName());
      assertFalse(basicMonthOfYearDateTimeField0.isLenient());
      assertEquals(13, basicMonthOfYearDateTimeField0.getMaximumValue());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      GregorianChronology gregorianChronology0 = GregorianChronology.getInstance();
      assertNotNull(gregorianChronology0);
      
      GJMonthOfYearDateTimeField gJMonthOfYearDateTimeField0 = new GJMonthOfYearDateTimeField(gregorianChronology0);
      assertNotNull(gJMonthOfYearDateTimeField0);
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      assertEquals(12, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      
      long long0 = gJMonthOfYearDateTimeField0.getDifferenceAsLong(2678399270L, (-1371L));
      assertEquals(1L, long0);
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      assertEquals(12, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      EthiopicChronology ethiopicChronology0 = EthiopicChronology.getInstanceUTC();
      assertNotNull(ethiopicChronology0);
      assertEquals(1, EthiopicChronology.EE);
      
      GJMonthOfYearDateTimeField gJMonthOfYearDateTimeField0 = new GJMonthOfYearDateTimeField(ethiopicChronology0);
      assertNotNull(gJMonthOfYearDateTimeField0);
      assertEquals(1, EthiopicChronology.EE);
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      assertEquals(13, gJMonthOfYearDateTimeField0.getMaximumValue());
      
      MonthDay monthDay0 = new MonthDay();
      assertNotNull(monthDay0);
      assertEquals(0, MonthDay.MONTH_OF_YEAR);
      assertEquals(1, MonthDay.DAY_OF_MONTH);
      assertEquals(14, monthDay0.getDayOfMonth());
      assertEquals(2, monthDay0.size());
      assertEquals(2, monthDay0.getMonthOfYear());
      
      int[] intArray0 = new int[9];
      // Undeclared exception!
      try { 
        gJMonthOfYearDateTimeField0.add((ReadablePartial) monthDay0, 1, intArray0, 1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Value 0 for monthOfYear must be in the range [1,13]
         //
         verifyException("org.joda.time.field.FieldUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      GregorianChronology gregorianChronology0 = GregorianChronology.getInstanceUTC();
      assertNotNull(gregorianChronology0);
      
      GJMonthOfYearDateTimeField gJMonthOfYearDateTimeField0 = new GJMonthOfYearDateTimeField(gregorianChronology0);
      assertNotNull(gJMonthOfYearDateTimeField0);
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertEquals(12, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      
      Partial partial0 = new Partial();
      assertNotNull(partial0);
      assertEquals(0, partial0.size());
      
      int[] intArray0 = new int[0];
      int[] intArray1 = gJMonthOfYearDateTimeField0.add((ReadablePartial) partial0, 2, intArray0, 2);
      assertNotNull(intArray1);
      assertArrayEquals(new int[] {}, intArray0);
      assertArrayEquals(new int[] {}, intArray1);
      assertNotSame(intArray0, intArray1);
      assertNotSame(intArray1, intArray0);
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertEquals(12, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      assertEquals(0, partial0.size());
      assertFalse(intArray1.equals((Object)intArray0));
      assertEquals(0, intArray0.length);
      assertEquals(0, intArray1.length);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      EthiopicChronology ethiopicChronology0 = EthiopicChronology.getInstance();
      assertNotNull(ethiopicChronology0);
      assertEquals(1, EthiopicChronology.EE);
      
      GJMonthOfYearDateTimeField gJMonthOfYearDateTimeField0 = new GJMonthOfYearDateTimeField(ethiopicChronology0);
      assertNotNull(gJMonthOfYearDateTimeField0);
      assertEquals(1, EthiopicChronology.EE);
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      assertEquals(13, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      
      MonthDay monthDay0 = new MonthDay(1, 1);
      assertNotNull(monthDay0);
      assertEquals(1, MonthDay.DAY_OF_MONTH);
      assertEquals(0, MonthDay.MONTH_OF_YEAR);
      assertEquals(2, monthDay0.size());
      assertEquals(1, monthDay0.getMonthOfYear());
      assertEquals(1, monthDay0.getDayOfMonth());
      
      int[] intArray0 = new int[2];
      int[] intArray1 = gJMonthOfYearDateTimeField0.add((ReadablePartial) monthDay0, 1, intArray0, 0);
      assertNotNull(intArray1);
      assertEquals(1, EthiopicChronology.EE);
      assertEquals(1, MonthDay.DAY_OF_MONTH);
      assertEquals(0, MonthDay.MONTH_OF_YEAR);
      assertArrayEquals(new int[] {0, 0}, intArray0);
      assertArrayEquals(new int[] {0, 0}, intArray1);
      assertSame(intArray0, intArray1);
      assertSame(intArray1, intArray0);
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      assertEquals(13, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertEquals(2, monthDay0.size());
      assertEquals(1, monthDay0.getMonthOfYear());
      assertEquals(1, monthDay0.getDayOfMonth());
      assertEquals(2, intArray0.length);
      assertEquals(2, intArray1.length);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      GregorianChronology gregorianChronology0 = GregorianChronology.getInstance();
      assertNotNull(gregorianChronology0);
      
      GJMonthOfYearDateTimeField gJMonthOfYearDateTimeField0 = new GJMonthOfYearDateTimeField(gregorianChronology0);
      assertNotNull(gJMonthOfYearDateTimeField0);
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      assertEquals(12, gJMonthOfYearDateTimeField0.getMaximumValue());
      
      long long0 = gJMonthOfYearDateTimeField0.add(1L, 2678399272L);
      assertEquals(7043509771776000001L, long0);
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      assertEquals(12, gJMonthOfYearDateTimeField0.getMaximumValue());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      EthiopicChronology ethiopicChronology0 = EthiopicChronology.getInstanceUTC();
      assertNotNull(ethiopicChronology0);
      assertEquals(1, EthiopicChronology.EE);
      
      GJMonthOfYearDateTimeField gJMonthOfYearDateTimeField0 = new GJMonthOfYearDateTimeField(ethiopicChronology0);
      assertNotNull(gJMonthOfYearDateTimeField0);
      assertEquals(1, EthiopicChronology.EE);
      assertEquals(13, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      
      // Undeclared exception!
      try { 
        gJMonthOfYearDateTimeField0.add(918518400000L, 918518400000L);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Magnitude of add amount is too large: 918518400000
         //
         verifyException("org.joda.time.chrono.BasicMonthOfYearDateTimeField", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TimeZone timeZone0 = TimeZone.getTimeZone("");
      assertNotNull(timeZone0);
      assertEquals("GMT", timeZone0.getID());
      
      DateTimeZone dateTimeZone0 = DateTimeZone.forTimeZone(timeZone0);
      assertNotNull(dateTimeZone0);
      assertEquals("GMT", timeZone0.getID());
      assertEquals("UTC", dateTimeZone0.getID());
      assertTrue(dateTimeZone0.isFixed());
      assertEquals("UTC", dateTimeZone0.toString());
      
      GregorianChronology gregorianChronology0 = GregorianChronology.getInstance(dateTimeZone0);
      assertNotNull(gregorianChronology0);
      assertEquals("GMT", timeZone0.getID());
      assertEquals("UTC", dateTimeZone0.getID());
      assertTrue(dateTimeZone0.isFixed());
      assertEquals("UTC", dateTimeZone0.toString());
      
      GJMonthOfYearDateTimeField gJMonthOfYearDateTimeField0 = new GJMonthOfYearDateTimeField(gregorianChronology0);
      assertNotNull(gJMonthOfYearDateTimeField0);
      assertEquals("GMT", timeZone0.getID());
      assertEquals("UTC", dateTimeZone0.getID());
      assertTrue(dateTimeZone0.isFixed());
      assertEquals("UTC", dateTimeZone0.toString());
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      assertEquals(12, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      
      // Undeclared exception!
      try { 
        gJMonthOfYearDateTimeField0.add((-62135596800045L), (-62135596800045L));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Magnitude of add amount is too large: -62135596800045
         //
         verifyException("org.joda.time.chrono.BasicMonthOfYearDateTimeField", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TimeZone timeZone0 = TimeZone.getTimeZone("");
      assertNotNull(timeZone0);
      assertEquals("GMT", timeZone0.getID());
      
      DateTimeZone dateTimeZone0 = DateTimeZone.forTimeZone(timeZone0);
      assertNotNull(dateTimeZone0);
      assertEquals("GMT", timeZone0.getID());
      assertTrue(dateTimeZone0.isFixed());
      assertEquals("UTC", dateTimeZone0.toString());
      assertEquals("UTC", dateTimeZone0.getID());
      
      GregorianChronology gregorianChronology0 = GregorianChronology.getInstance(dateTimeZone0);
      assertNotNull(gregorianChronology0);
      assertEquals("GMT", timeZone0.getID());
      assertTrue(dateTimeZone0.isFixed());
      assertEquals("UTC", dateTimeZone0.toString());
      assertEquals("UTC", dateTimeZone0.getID());
      
      GJMonthOfYearDateTimeField gJMonthOfYearDateTimeField0 = new GJMonthOfYearDateTimeField(gregorianChronology0);
      assertNotNull(gJMonthOfYearDateTimeField0);
      assertEquals("GMT", timeZone0.getID());
      assertTrue(dateTimeZone0.isFixed());
      assertEquals("UTC", dateTimeZone0.toString());
      assertEquals("UTC", dateTimeZone0.getID());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertEquals(12, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      
      // Undeclared exception!
      try { 
        gJMonthOfYearDateTimeField0.add((-62135596800059L), (-62135596800059L));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Magnitude of add amount is too large: -62135596800059
         //
         verifyException("org.joda.time.chrono.BasicMonthOfYearDateTimeField", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      GregorianChronology gregorianChronology0 = GregorianChronology.getInstance();
      assertNotNull(gregorianChronology0);
      
      GJMonthOfYearDateTimeField gJMonthOfYearDateTimeField0 = new GJMonthOfYearDateTimeField(gregorianChronology0);
      assertNotNull(gJMonthOfYearDateTimeField0);
      assertEquals(12, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      
      long long0 = gJMonthOfYearDateTimeField0.add((-1371L), 2678399270L);
      assertEquals(7043509766505598629L, long0);
      assertEquals(12, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      GregorianChronology gregorianChronology0 = GregorianChronology.getInstance();
      assertNotNull(gregorianChronology0);
      
      GJMonthOfYearDateTimeField gJMonthOfYearDateTimeField0 = new GJMonthOfYearDateTimeField(gregorianChronology0);
      assertNotNull(gJMonthOfYearDateTimeField0);
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      assertEquals(12, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      
      long long0 = gJMonthOfYearDateTimeField0.add((-183L), (-183L));
      assertEquals((-481334400183L), long0);
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      assertEquals(12, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      GregorianChronology gregorianChronology0 = GregorianChronology.getInstance();
      assertNotNull(gregorianChronology0);
      
      GJMonthOfYearDateTimeField gJMonthOfYearDateTimeField0 = new GJMonthOfYearDateTimeField(gregorianChronology0);
      assertNotNull(gJMonthOfYearDateTimeField0);
      assertEquals(12, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      
      long long0 = gJMonthOfYearDateTimeField0.add((-880L), (-503L));
      assertEquals((-1322784000880L), long0);
      assertEquals(12, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      EthiopicChronology ethiopicChronology0 = EthiopicChronology.getInstance();
      assertNotNull(ethiopicChronology0);
      assertEquals(1, EthiopicChronology.EE);
      
      GJMonthOfYearDateTimeField gJMonthOfYearDateTimeField0 = new GJMonthOfYearDateTimeField(ethiopicChronology0);
      assertNotNull(gJMonthOfYearDateTimeField0);
      assertEquals(1, EthiopicChronology.EE);
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      assertEquals(13, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      
      long long0 = gJMonthOfYearDateTimeField0.add(300L, (long) 0);
      assertEquals(1, EthiopicChronology.EE);
      assertEquals(300L, long0);
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      assertEquals(13, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      EthiopicChronology ethiopicChronology0 = EthiopicChronology.getInstance();
      assertNotNull(ethiopicChronology0);
      assertEquals(1, EthiopicChronology.EE);
      
      int[] intArray0 = new int[2];
      GJMonthOfYearDateTimeField gJMonthOfYearDateTimeField0 = new GJMonthOfYearDateTimeField(ethiopicChronology0);
      assertNotNull(gJMonthOfYearDateTimeField0);
      assertEquals(1, EthiopicChronology.EE);
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertEquals(13, gJMonthOfYearDateTimeField0.getMaximumValue());
      
      LocalDateTime localDateTime0 = LocalDateTime.now();
      assertNotNull(localDateTime0);
      assertEquals(4, localDateTime0.size());
      
      // Undeclared exception!
      try { 
        gJMonthOfYearDateTimeField0.add((ReadablePartial) localDateTime0, (-222), intArray0, (-222));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Value 0 for year is not supported
         //
         verifyException("org.joda.time.field.SkipDateTimeField", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      JulianChronology julianChronology0 = JulianChronology.getInstanceUTC();
      assertNotNull(julianChronology0);
      
      GJMonthOfYearDateTimeField gJMonthOfYearDateTimeField0 = new GJMonthOfYearDateTimeField(julianChronology0);
      assertNotNull(gJMonthOfYearDateTimeField0);
      assertEquals(12, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      
      long long0 = gJMonthOfYearDateTimeField0.addWrapField(0L, (-3004));
      assertEquals((-10540800000L), long0);
      assertEquals(12, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      FixedDateTimeZone fixedDateTimeZone0 = (FixedDateTimeZone)DateTimeZone.UTC;
      assertNotNull(fixedDateTimeZone0);
      assertEquals("UTC", fixedDateTimeZone0.toString());
      assertTrue(fixedDateTimeZone0.isFixed());
      assertEquals("UTC", fixedDateTimeZone0.getID());
      
      GregorianChronology gregorianChronology0 = GregorianChronology.getInstance((DateTimeZone) fixedDateTimeZone0);
      assertNotNull(gregorianChronology0);
      assertEquals("UTC", fixedDateTimeZone0.toString());
      assertTrue(fixedDateTimeZone0.isFixed());
      assertEquals("UTC", fixedDateTimeZone0.getID());
      
      GJMonthOfYearDateTimeField gJMonthOfYearDateTimeField0 = new GJMonthOfYearDateTimeField(gregorianChronology0);
      assertNotNull(gJMonthOfYearDateTimeField0);
      assertEquals("UTC", fixedDateTimeZone0.toString());
      assertTrue(fixedDateTimeZone0.isFixed());
      assertEquals("UTC", fixedDateTimeZone0.getID());
      assertEquals(12, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      
      boolean boolean0 = gJMonthOfYearDateTimeField0.isLenient();
      assertFalse(boolean0);
      assertEquals("UTC", fixedDateTimeZone0.toString());
      assertTrue(fixedDateTimeZone0.isFixed());
      assertEquals("UTC", fixedDateTimeZone0.getID());
      assertEquals(12, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      EthiopicChronology ethiopicChronology0 = EthiopicChronology.getInstanceUTC();
      assertNotNull(ethiopicChronology0);
      assertEquals(1, EthiopicChronology.EE);
      
      GJMonthOfYearDateTimeField gJMonthOfYearDateTimeField0 = new GJMonthOfYearDateTimeField(ethiopicChronology0);
      assertNotNull(gJMonthOfYearDateTimeField0);
      assertEquals(1, EthiopicChronology.EE);
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertEquals(13, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      
      MonthDay monthDay0 = new MonthDay();
      assertNotNull(monthDay0);
      assertEquals(1, MonthDay.DAY_OF_MONTH);
      assertEquals(0, MonthDay.MONTH_OF_YEAR);
      assertEquals(14, monthDay0.getDayOfMonth());
      assertEquals(2, monthDay0.getMonthOfYear());
      assertEquals(2, monthDay0.size());
      
      int[] intArray0 = new int[9];
      int[] intArray1 = gJMonthOfYearDateTimeField0.add((ReadablePartial) monthDay0, 0, intArray0, 1);
      assertNotNull(intArray1);
      assertEquals(1, EthiopicChronology.EE);
      assertEquals(1, MonthDay.DAY_OF_MONTH);
      assertEquals(0, MonthDay.MONTH_OF_YEAR);
      assertArrayEquals(new int[] {3, 1, 0, 0, 0, 0, 0, 0, 0}, intArray0);
      assertArrayEquals(new int[] {3, 1, 0, 0, 0, 0, 0, 0, 0}, intArray1);
      assertSame(intArray0, intArray1);
      assertSame(intArray1, intArray0);
      assertEquals("monthOfYear", gJMonthOfYearDateTimeField0.getName());
      assertTrue(gJMonthOfYearDateTimeField0.isSupported());
      assertEquals(1, gJMonthOfYearDateTimeField0.getMinimumValue());
      assertEquals(13, gJMonthOfYearDateTimeField0.getMaximumValue());
      assertFalse(gJMonthOfYearDateTimeField0.isLenient());
      assertEquals(14, monthDay0.getDayOfMonth());
      assertEquals(2, monthDay0.getMonthOfYear());
      assertEquals(2, monthDay0.size());
      assertEquals(9, intArray0.length);
      assertEquals(9, intArray1.length);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      CopticChronology copticChronology0 = CopticChronology.getInstanceUTC();
      assertNotNull(copticChronology0);
      assertEquals(1, CopticChronology.AM);
      
      BasicMonthOfYearDateTimeField basicMonthOfYearDateTimeField0 = new BasicMonthOfYearDateTimeField(copticChronology0, 1);
      assertNotNull(basicMonthOfYearDateTimeField0);
      assertEquals(1, CopticChronology.AM);
      assertFalse(basicMonthOfYearDateTimeField0.isLenient());
      assertEquals("monthOfYear", basicMonthOfYearDateTimeField0.getName());
      assertTrue(basicMonthOfYearDateTimeField0.isSupported());
      assertEquals(13, basicMonthOfYearDateTimeField0.getMaximumValue());
      assertEquals(1, basicMonthOfYearDateTimeField0.getMinimumValue());
      
      long long0 = basicMonthOfYearDateTimeField0.remainder(1);
      assertEquals(1, CopticChronology.AM);
      assertEquals(1900800001L, long0);
      assertFalse(basicMonthOfYearDateTimeField0.isLenient());
      assertEquals("monthOfYear", basicMonthOfYearDateTimeField0.getName());
      assertTrue(basicMonthOfYearDateTimeField0.isSupported());
      assertEquals(13, basicMonthOfYearDateTimeField0.getMaximumValue());
      assertEquals(1, basicMonthOfYearDateTimeField0.getMinimumValue());
  }
}
