/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 04 21:43:33 GMT 2026
 */

package org.apache.commons.collections.map;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.collections.map.AbstractHashedMap;
import org.apache.commons.collections.map.CaseInsensitiveMap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CaseInsensitiveMap_ESTest extends CaseInsensitiveMap_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CaseInsensitiveMap caseInsensitiveMap0 = new CaseInsensitiveMap();
      assertTrue(caseInsensitiveMap0.isEmpty());
      assertEquals(0, caseInsensitiveMap0.size());
      assertNotNull(caseInsensitiveMap0);
      
      Object object0 = caseInsensitiveMap0.putIfAbsent(caseInsensitiveMap0, caseInsensitiveMap0);
      assertEquals(1, caseInsensitiveMap0.size());
      assertFalse(caseInsensitiveMap0.isEmpty());
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CaseInsensitiveMap caseInsensitiveMap0 = new CaseInsensitiveMap();
      assertEquals(0, caseInsensitiveMap0.size());
      assertTrue(caseInsensitiveMap0.isEmpty());
      assertNotNull(caseInsensitiveMap0);
      
      Object object0 = caseInsensitiveMap0.convertKey((Object) null);
      assertEquals(0, caseInsensitiveMap0.size());
      assertTrue(caseInsensitiveMap0.isEmpty());
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CaseInsensitiveMap caseInsensitiveMap0 = new CaseInsensitiveMap();
      assertTrue(caseInsensitiveMap0.isEmpty());
      assertEquals(0, caseInsensitiveMap0.size());
      assertNotNull(caseInsensitiveMap0);
      
      CaseInsensitiveMap caseInsensitiveMap1 = (CaseInsensitiveMap)caseInsensitiveMap0.clone();
      assertNotSame(caseInsensitiveMap0, caseInsensitiveMap1);
      assertNotSame(caseInsensitiveMap1, caseInsensitiveMap0);
      assertTrue(caseInsensitiveMap0.isEmpty());
      assertEquals(0, caseInsensitiveMap0.size());
      assertTrue(caseInsensitiveMap1.isEmpty());
      assertEquals(0, caseInsensitiveMap1.size());
      assertNotNull(caseInsensitiveMap1);
      assertTrue(caseInsensitiveMap1.equals((Object)caseInsensitiveMap0));
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AbstractHashedMap abstractHashedMap0 = new AbstractHashedMap(16, 16);
      assertTrue(abstractHashedMap0.isEmpty());
      assertEquals(0, abstractHashedMap0.size());
      assertNotNull(abstractHashedMap0);
      
      CaseInsensitiveMap caseInsensitiveMap0 = new CaseInsensitiveMap(abstractHashedMap0);
      assertTrue(abstractHashedMap0.isEmpty());
      assertEquals(0, abstractHashedMap0.size());
      assertTrue(caseInsensitiveMap0.isEmpty());
      assertEquals(0, caseInsensitiveMap0.size());
      assertNotNull(caseInsensitiveMap0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CaseInsensitiveMap caseInsensitiveMap0 = new CaseInsensitiveMap(16, 16);
      assertEquals(0, caseInsensitiveMap0.size());
      assertTrue(caseInsensitiveMap0.isEmpty());
      assertNotNull(caseInsensitiveMap0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CaseInsensitiveMap caseInsensitiveMap0 = new CaseInsensitiveMap(38);
      assertEquals(0, caseInsensitiveMap0.size());
      assertTrue(caseInsensitiveMap0.isEmpty());
      assertNotNull(caseInsensitiveMap0);
  }
}
