/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 05 04:19:51 GMT 2026
 */

package org.apache.commons.math.linear;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.math.linear.CholeskyDecompositionImpl;
import org.apache.commons.math.linear.DecompositionSolver;
import org.apache.commons.math.linear.DenseRealMatrix;
import org.apache.commons.math.linear.OpenMapRealVector;
import org.apache.commons.math.linear.RealMatrix;
import org.apache.commons.math.linear.RealMatrixImpl;
import org.apache.commons.math.linear.RealVector;
import org.apache.commons.math.linear.RealVectorImpl;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CholeskyDecompositionImpl_ESTest extends CholeskyDecompositionImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      double[] doubleArray0 = new double[1];
      RealMatrixImpl realMatrixImpl0 = new RealMatrixImpl(doubleArray0);
      assertNotNull(realMatrixImpl0);
      assertEquals(1, doubleArray0.length);
      assertEquals(1, realMatrixImpl0.getColumnDimension());
      assertEquals(1, realMatrixImpl0.getRowDimension());
      assertArrayEquals(new double[] {0.0}, doubleArray0, 0.01);
      
      CholeskyDecompositionImpl choleskyDecompositionImpl0 = new CholeskyDecompositionImpl(realMatrixImpl0, 951.63, 0.0);
      assertNotNull(choleskyDecompositionImpl0);
      assertEquals(1, doubleArray0.length);
      assertEquals(1, realMatrixImpl0.getColumnDimension());
      assertEquals(1, realMatrixImpl0.getRowDimension());
      assertEquals(0.0, choleskyDecompositionImpl0.getDeterminant(), 0.01);
      assertArrayEquals(new double[] {0.0}, doubleArray0, 0.01);
      assertEquals(1.0E-15, CholeskyDecompositionImpl.DEFAULT_RELATIVE_SYMMETRY_THRESHOLD, 0.01);
      assertEquals(1.0E-10, CholeskyDecompositionImpl.DEFAULT_ABSOLUTE_POSITIVITY_THRESHOLD, 0.01);
      
      double double0 = choleskyDecompositionImpl0.getDeterminant();
      assertEquals(1, doubleArray0.length);
      assertEquals(1, realMatrixImpl0.getColumnDimension());
      assertEquals(1, realMatrixImpl0.getRowDimension());
      assertEquals(0.0, choleskyDecompositionImpl0.getDeterminant(), 0.01);
      assertEquals(0.0, double0, 0.01);
      assertArrayEquals(new double[] {0.0}, doubleArray0, 0.01);
      assertEquals(1.0E-15, CholeskyDecompositionImpl.DEFAULT_RELATIVE_SYMMETRY_THRESHOLD, 0.01);
      assertEquals(1.0E-10, CholeskyDecompositionImpl.DEFAULT_ABSOLUTE_POSITIVITY_THRESHOLD, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      double[] doubleArray0 = new double[1];
      RealMatrixImpl realMatrixImpl0 = new RealMatrixImpl(doubleArray0);
      assertNotNull(realMatrixImpl0);
      assertEquals(1, doubleArray0.length);
      assertEquals(1, realMatrixImpl0.getRowDimension());
      assertEquals(1, realMatrixImpl0.getColumnDimension());
      assertArrayEquals(new double[] {0.0}, doubleArray0, 0.01);
      
      CholeskyDecompositionImpl choleskyDecompositionImpl0 = new CholeskyDecompositionImpl(realMatrixImpl0, (-1479.82611135904), (-1479.82611135904));
      assertNotNull(choleskyDecompositionImpl0);
      assertEquals(1, doubleArray0.length);
      assertEquals(1, realMatrixImpl0.getRowDimension());
      assertEquals(1, realMatrixImpl0.getColumnDimension());
      assertEquals(0.0, choleskyDecompositionImpl0.getDeterminant(), 0.01);
      assertArrayEquals(new double[] {0.0}, doubleArray0, 0.01);
      assertEquals(1.0E-10, CholeskyDecompositionImpl.DEFAULT_ABSOLUTE_POSITIVITY_THRESHOLD, 0.01);
      assertEquals(1.0E-15, CholeskyDecompositionImpl.DEFAULT_RELATIVE_SYMMETRY_THRESHOLD, 0.01);
      
      DenseRealMatrix denseRealMatrix0 = (DenseRealMatrix)choleskyDecompositionImpl0.getLT();
      assertNotNull(denseRealMatrix0);
      assertEquals(1, doubleArray0.length);
      assertEquals(1, realMatrixImpl0.getRowDimension());
      assertEquals(1, realMatrixImpl0.getColumnDimension());
      assertEquals(0.0, choleskyDecompositionImpl0.getDeterminant(), 0.01);
      assertEquals(0.0, denseRealMatrix0.getFrobeniusNorm(), 0.01);
      assertEquals(1, denseRealMatrix0.getRowDimension());
      assertEquals(1, denseRealMatrix0.getColumnDimension());
      assertArrayEquals(new double[] {0.0}, doubleArray0, 0.01);
      assertEquals(1.0E-10, CholeskyDecompositionImpl.DEFAULT_ABSOLUTE_POSITIVITY_THRESHOLD, 0.01);
      assertEquals(1.0E-15, CholeskyDecompositionImpl.DEFAULT_RELATIVE_SYMMETRY_THRESHOLD, 0.01);
      assertEquals(52, DenseRealMatrix.BLOCK_SIZE);
      
      DenseRealMatrix denseRealMatrix1 = (DenseRealMatrix)choleskyDecompositionImpl0.getLT();
      assertNotNull(denseRealMatrix1);
      assertEquals(1, doubleArray0.length);
      assertEquals(1, realMatrixImpl0.getRowDimension());
      assertEquals(1, realMatrixImpl0.getColumnDimension());
      assertEquals(0.0, choleskyDecompositionImpl0.getDeterminant(), 0.01);
      assertEquals(1, denseRealMatrix1.getRowDimension());
      assertEquals(0.0, denseRealMatrix1.getFrobeniusNorm(), 0.01);
      assertEquals(1, denseRealMatrix1.getColumnDimension());
      assertArrayEquals(new double[] {0.0}, doubleArray0, 0.01);
      assertEquals(1.0E-10, CholeskyDecompositionImpl.DEFAULT_ABSOLUTE_POSITIVITY_THRESHOLD, 0.01);
      assertEquals(1.0E-15, CholeskyDecompositionImpl.DEFAULT_RELATIVE_SYMMETRY_THRESHOLD, 0.01);
      assertEquals(52, DenseRealMatrix.BLOCK_SIZE);
      assertSame(denseRealMatrix1, denseRealMatrix0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      double[] doubleArray0 = new double[1];
      RealMatrixImpl realMatrixImpl0 = new RealMatrixImpl(doubleArray0);
      assertNotNull(realMatrixImpl0);
      assertEquals(1, doubleArray0.length);
      assertEquals(1, realMatrixImpl0.getColumnDimension());
      assertEquals(1, realMatrixImpl0.getRowDimension());
      assertArrayEquals(new double[] {0.0}, doubleArray0, 0.01);
      
      CholeskyDecompositionImpl choleskyDecompositionImpl0 = new CholeskyDecompositionImpl(realMatrixImpl0, (-1479.82611135904), (-1479.82611135904));
      assertNotNull(choleskyDecompositionImpl0);
      assertEquals(1, doubleArray0.length);
      assertEquals(1, realMatrixImpl0.getColumnDimension());
      assertEquals(1, realMatrixImpl0.getRowDimension());
      assertEquals(0.0, choleskyDecompositionImpl0.getDeterminant(), 0.01);
      assertArrayEquals(new double[] {0.0}, doubleArray0, 0.01);
      assertEquals(1.0E-10, CholeskyDecompositionImpl.DEFAULT_ABSOLUTE_POSITIVITY_THRESHOLD, 0.01);
      assertEquals(1.0E-15, CholeskyDecompositionImpl.DEFAULT_RELATIVE_SYMMETRY_THRESHOLD, 0.01);
      
      DenseRealMatrix denseRealMatrix0 = (DenseRealMatrix)choleskyDecompositionImpl0.getL();
      assertNotNull(denseRealMatrix0);
      assertEquals(1, doubleArray0.length);
      assertEquals(1, realMatrixImpl0.getColumnDimension());
      assertEquals(1, realMatrixImpl0.getRowDimension());
      assertEquals(0.0, choleskyDecompositionImpl0.getDeterminant(), 0.01);
      assertEquals(1, denseRealMatrix0.getColumnDimension());
      assertEquals(1, denseRealMatrix0.getRowDimension());
      assertEquals(0.0, denseRealMatrix0.getFrobeniusNorm(), 0.01);
      assertArrayEquals(new double[] {0.0}, doubleArray0, 0.01);
      assertEquals(1.0E-10, CholeskyDecompositionImpl.DEFAULT_ABSOLUTE_POSITIVITY_THRESHOLD, 0.01);
      assertEquals(1.0E-15, CholeskyDecompositionImpl.DEFAULT_RELATIVE_SYMMETRY_THRESHOLD, 0.01);
      assertEquals(52, DenseRealMatrix.BLOCK_SIZE);
      
      DenseRealMatrix denseRealMatrix1 = (DenseRealMatrix)choleskyDecompositionImpl0.getL();
      assertNotNull(denseRealMatrix1);
      assertEquals(1, doubleArray0.length);
      assertEquals(1, realMatrixImpl0.getColumnDimension());
      assertEquals(1, realMatrixImpl0.getRowDimension());
      assertEquals(0.0, choleskyDecompositionImpl0.getDeterminant(), 0.01);
      assertEquals(1, denseRealMatrix1.getRowDimension());
      assertEquals(1, denseRealMatrix1.getColumnDimension());
      assertEquals(0.0, denseRealMatrix1.getFrobeniusNorm(), 0.01);
      assertArrayEquals(new double[] {0.0}, doubleArray0, 0.01);
      assertEquals(1.0E-10, CholeskyDecompositionImpl.DEFAULT_ABSOLUTE_POSITIVITY_THRESHOLD, 0.01);
      assertEquals(1.0E-15, CholeskyDecompositionImpl.DEFAULT_RELATIVE_SYMMETRY_THRESHOLD, 0.01);
      assertEquals(52, DenseRealMatrix.BLOCK_SIZE);
      assertSame(denseRealMatrix1, denseRealMatrix0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      double[] doubleArray0 = new double[7];
      doubleArray0[0] = 1.0;
      RealVectorImpl realVectorImpl0 = new RealVectorImpl(doubleArray0);
      assertNotNull(realVectorImpl0);
      assertEquals(7, doubleArray0.length);
      assertEquals(64.0, realVectorImpl0.getLInfNorm(), 0.01);
      assertEquals(7, realVectorImpl0.getDimension());
      assertEquals(1.0, realVectorImpl0.getL1Norm(), 0.01);
      assertEquals(1.0, realVectorImpl0.getNorm(), 0.01);
      assertFalse(realVectorImpl0.isInfinite());
      assertFalse(realVectorImpl0.isNaN());
      assertArrayEquals(new double[] {1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0}, doubleArray0, 0.01);
      
      DenseRealMatrix denseRealMatrix0 = (DenseRealMatrix)realVectorImpl0.outerProduct(doubleArray0);
      assertNotNull(denseRealMatrix0);
      assertEquals(7, doubleArray0.length);
      assertEquals(64.0, realVectorImpl0.getLInfNorm(), 0.01);
      assertEquals(7, realVectorImpl0.getDimension());
      assertEquals(1.0, realVectorImpl0.getL1Norm(), 0.01);
      assertEquals(1.0, realVectorImpl0.getNorm(), 0.01);
      assertFalse(realVectorImpl0.isInfinite());
      assertFalse(realVectorImpl0.isNaN());
      assertEquals(7, denseRealMatrix0.getColumnDimension());
      assertEquals(1.0, denseRealMatrix0.getFrobeniusNorm(), 0.01);
      assertEquals(7, denseRealMatrix0.getRowDimension());
      assertArrayEquals(new double[] {1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0}, doubleArray0, 0.01);
      assertEquals(52, DenseRealMatrix.BLOCK_SIZE);
      
      CholeskyDecompositionImpl choleskyDecompositionImpl0 = null;
      try {
        choleskyDecompositionImpl0 = new CholeskyDecompositionImpl(denseRealMatrix0);
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // not positive definite matrix
         //
         verifyException("org.apache.commons.math.linear.CholeskyDecompositionImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      double[] doubleArray0 = new double[6];
      doubleArray0[0] = 1.0;
      doubleArray0[1] = (-3861.2824912315423);
      OpenMapRealVector openMapRealVector0 = new OpenMapRealVector(doubleArray0, 1.0E-15);
      assertNotNull(openMapRealVector0);
      assertEquals(6, doubleArray0.length);
      assertEquals(0.3333333333333333, openMapRealVector0.getSparcity(), 0.01);
      assertEquals(1.0E-15, openMapRealVector0.getEpsilon(), 0.01);
      assertEquals(6, openMapRealVector0.getDimension());
      assertArrayEquals(new double[] {1.0, (-3861.2824912315423), 0.0, 0.0, 0.0, 0.0}, doubleArray0, 0.01);
      assertEquals(1.0E-12, OpenMapRealVector.DEFAULT_ZERO_TOLERANCE, 0.01);
      
      RealMatrix realMatrix0 = openMapRealVector0.outerProduct((RealVector) openMapRealVector0);
      assertNotNull(realMatrix0);
      assertEquals(6, doubleArray0.length);
      assertEquals(0.3333333333333333, openMapRealVector0.getSparcity(), 0.01);
      assertEquals(1.0E-15, openMapRealVector0.getEpsilon(), 0.01);
      assertEquals(6, openMapRealVector0.getDimension());
      assertEquals(6, realMatrix0.getRowDimension());
      assertEquals(6, realMatrix0.getColumnDimension());
      assertArrayEquals(new double[] {1.0, (-3861.2824912315423), 0.0, 0.0, 0.0, 0.0}, doubleArray0, 0.01);
      assertEquals(1.0E-12, OpenMapRealVector.DEFAULT_ZERO_TOLERANCE, 0.01);
      
      CholeskyDecompositionImpl choleskyDecompositionImpl0 = null;
      try {
        choleskyDecompositionImpl0 = new CholeskyDecompositionImpl(realMatrix0, (-3861.2824912315423), 1.0);
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // not symmetric matrix
         //
         verifyException("org.apache.commons.math.linear.CholeskyDecompositionImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      DenseRealMatrix denseRealMatrix0 = new DenseRealMatrix(372, 4);
      assertNotNull(denseRealMatrix0);
      assertEquals(4, denseRealMatrix0.getColumnDimension());
      assertEquals(0.0, denseRealMatrix0.getFrobeniusNorm(), 0.01);
      assertEquals(372, denseRealMatrix0.getRowDimension());
      assertEquals(52, DenseRealMatrix.BLOCK_SIZE);
      
      CholeskyDecompositionImpl choleskyDecompositionImpl0 = null;
      try {
        choleskyDecompositionImpl0 = new CholeskyDecompositionImpl(denseRealMatrix0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // a 372x4 matrix was provided instead of a square matrix
         //
         verifyException("org.apache.commons.math.linear.CholeskyDecompositionImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      RealMatrixImpl realMatrixImpl0 = new RealMatrixImpl();
      assertNotNull(realMatrixImpl0);
      assertEquals(0, realMatrixImpl0.getColumnDimension());
      assertEquals(0, realMatrixImpl0.getRowDimension());
      
      CholeskyDecompositionImpl choleskyDecompositionImpl0 = new CholeskyDecompositionImpl(realMatrixImpl0, 740, 740);
      assertNotNull(choleskyDecompositionImpl0);
      assertEquals(0, realMatrixImpl0.getColumnDimension());
      assertEquals(0, realMatrixImpl0.getRowDimension());
      assertEquals(1.0, choleskyDecompositionImpl0.getDeterminant(), 0.01);
      assertEquals(1.0E-10, CholeskyDecompositionImpl.DEFAULT_ABSOLUTE_POSITIVITY_THRESHOLD, 0.01);
      assertEquals(1.0E-15, CholeskyDecompositionImpl.DEFAULT_RELATIVE_SYMMETRY_THRESHOLD, 0.01);
      
      DecompositionSolver decompositionSolver0 = choleskyDecompositionImpl0.getSolver();
      assertNotNull(decompositionSolver0);
      assertEquals(0, realMatrixImpl0.getColumnDimension());
      assertEquals(0, realMatrixImpl0.getRowDimension());
      assertEquals(1.0, choleskyDecompositionImpl0.getDeterminant(), 0.01);
      assertTrue(decompositionSolver0.isNonSingular());
      assertEquals(1.0E-10, CholeskyDecompositionImpl.DEFAULT_ABSOLUTE_POSITIVITY_THRESHOLD, 0.01);
      assertEquals(1.0E-15, CholeskyDecompositionImpl.DEFAULT_RELATIVE_SYMMETRY_THRESHOLD, 0.01);
  }
}
