/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 05 01:17:51 GMT 2026
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.Attributes;
import org.jsoup.nodes.DataNode;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.nodes.Node;
import org.jsoup.nodes.TextNode;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Node_ESTest extends Node_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TextNode textNode0 = TextNode.createFromEncoded("/LdxW", "/LdxW");
      assertEquals("/LdxW", textNode0.baseUri());
      assertEquals("#text", textNode0.nodeName());
      assertEquals(0, (int)textNode0.siblingIndex());
      assertNotNull(textNode0);
      
      Node node0 = textNode0.clone();
      assertFalse(node0.equals((Object)textNode0));
      assertNotSame(textNode0, node0);
      assertNotSame(node0, textNode0);
      assertEquals("/LdxW", textNode0.baseUri());
      assertEquals("#text", textNode0.nodeName());
      assertEquals(0, (int)textNode0.siblingIndex());
      assertEquals(0, (int)node0.siblingIndex());
      assertEquals("/LdxW", node0.baseUri());
      assertEquals("#text", node0.nodeName());
      assertNotNull(node0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Document document0 = Document.createShell("OOwbW");
      assertEquals("OOwbW", document0.baseUri());
      assertEquals("#document", document0.nodeName());
      assertEquals(0, (int)document0.siblingIndex());
      assertFalse(document0.isBlock());
      assertNotNull(document0);
      
      TextNode textNode0 = new TextNode("OOwbW", "OOwbW");
      assertEquals("OOwbW", textNode0.baseUri());
      assertEquals("#text", textNode0.nodeName());
      assertEquals(0, (int)textNode0.siblingIndex());
      assertNotNull(textNode0);
      
      textNode0.parentNode = (Node) document0;
      assertEquals("OOwbW", document0.baseUri());
      assertEquals("#document", document0.nodeName());
      assertEquals(0, (int)document0.siblingIndex());
      assertFalse(document0.isBlock());
      assertEquals("OOwbW", textNode0.baseUri());
      assertEquals("#text", textNode0.nodeName());
      assertEquals(0, (int)textNode0.siblingIndex());
      assertEquals(0, (int)textNode0.parentNode.siblingIndex());
      assertEquals("OOwbW", textNode0.parentNode.baseUri());
      
      textNode0.hashCode();
      assertEquals("OOwbW", textNode0.baseUri());
      assertEquals("#text", textNode0.nodeName());
      assertEquals(0, (int)textNode0.siblingIndex());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TextNode textNode0 = new TextNode("/LidxW", "/LidxW");
      assertEquals("/LidxW", textNode0.baseUri());
      assertEquals(0, (int)textNode0.siblingIndex());
      assertEquals("#text", textNode0.nodeName());
      assertNotNull(textNode0);
      
      boolean boolean0 = textNode0.equals(textNode0);
      assertEquals("/LidxW", textNode0.baseUri());
      assertEquals(0, (int)textNode0.siblingIndex());
      assertEquals("#text", textNode0.nodeName());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TextNode textNode0 = TextNode.createFromEncoded("/LdxW", "/LdxW");
      assertEquals("/LdxW", textNode0.baseUri());
      assertEquals("#text", textNode0.nodeName());
      assertEquals(0, (int)textNode0.siblingIndex());
      assertNotNull(textNode0);
      
      boolean boolean0 = textNode0.equals("/LdxW");
      assertEquals("/LdxW", textNode0.baseUri());
      assertEquals("#text", textNode0.nodeName());
      assertEquals(0, (int)textNode0.siblingIndex());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Document document0 = Document.createShell("lOdbW");
      assertEquals("lOdbW", document0.baseUri());
      assertEquals("#document", document0.nodeName());
      assertEquals(0, (int)document0.siblingIndex());
      assertFalse(document0.isBlock());
      assertNotNull(document0);
      
      TextNode textNode0 = new TextNode("lOdbW", "o*^3uh.'+`%");
      assertEquals(0, (int)textNode0.siblingIndex());
      assertEquals("#text", textNode0.nodeName());
      assertEquals("o*^3uh.'+`%", textNode0.baseUri());
      assertNotNull(textNode0);
      
      Node[] nodeArray0 = new Node[2];
      nodeArray0[0] = (Node) textNode0;
      nodeArray0[1] = (Node) textNode0;
      document0.addChildren(nodeArray0);
      assertEquals(2, nodeArray0.length);
      assertEquals("lOdbW", document0.baseUri());
      assertEquals("#document", document0.nodeName());
      assertEquals(0, (int)document0.siblingIndex());
      assertFalse(document0.isBlock());
      
      Element element0 = (Element)textNode0.previousSibling();
      assertEquals(1, (int)textNode0.siblingIndex());
      assertEquals("#text", textNode0.nodeName());
      assertEquals("o*^3uh.'+`%", textNode0.baseUri());
      assertTrue(element0.isBlock());
      assertEquals(0, (int)element0.siblingIndex());
      assertEquals("lOdbW", element0.baseUri());
      assertNotNull(element0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TextNode textNode0 = TextNode.createFromEncoded("/LdxW", "/LdxW");
      assertEquals("#text", textNode0.nodeName());
      assertEquals(0, (int)textNode0.siblingIndex());
      assertEquals("/LdxW", textNode0.baseUri());
      assertNotNull(textNode0);
      
      textNode0.parentNode = (Node) textNode0;
      assertEquals("#text", textNode0.nodeName());
      assertEquals(0, (int)textNode0.siblingIndex());
      assertEquals("/LdxW", textNode0.baseUri());
      assertEquals(0, (int)textNode0.parentNode.siblingIndex());
      assertEquals("/LdxW", textNode0.parentNode.baseUri());
      
      Node node0 = textNode0.previousSibling();
      assertEquals("#text", textNode0.nodeName());
      assertEquals(0, (int)textNode0.siblingIndex());
      assertEquals("/LdxW", textNode0.baseUri());
      assertNull(node0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Document document0 = new Document("");
      assertEquals(0, (int)document0.siblingIndex());
      assertEquals("#document", document0.nodeName());
      assertFalse(document0.isBlock());
      assertEquals("", document0.baseUri());
      assertNotNull(document0);
      
      Document document1 = document0.normalise();
      assertSame(document0, document1);
      assertSame(document1, document0);
      assertEquals(0, (int)document0.siblingIndex());
      assertEquals("#document", document0.nodeName());
      assertFalse(document0.isBlock());
      assertEquals("", document0.baseUri());
      assertEquals(0, (int)document1.siblingIndex());
      assertEquals("#document", document1.nodeName());
      assertFalse(document1.isBlock());
      assertEquals("", document1.baseUri());
      assertNotNull(document1);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TextNode textNode0 = new TextNode("/LdxW", "/LdxW");
      assertEquals("/LdxW", textNode0.baseUri());
      assertEquals("#text", textNode0.nodeName());
      assertEquals(0, (int)textNode0.siblingIndex());
      assertNotNull(textNode0);
      
      // Undeclared exception!
      try { 
        textNode0.removeChild(textNode0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Must be true
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Document document0 = new Document("LM3& Wv&'#I");
      assertEquals(0, (int)document0.siblingIndex());
      assertEquals("LM3& Wv&'#I", document0.baseUri());
      assertEquals("#document", document0.nodeName());
      assertFalse(document0.isBlock());
      assertNotNull(document0);
      
      Element element0 = document0.appendElement("LM3& Wv&'#I");
      assertEquals(0, (int)document0.siblingIndex());
      assertEquals("LM3& Wv&'#I", document0.baseUri());
      assertEquals("#document", document0.nodeName());
      assertFalse(document0.isBlock());
      assertFalse(element0.isBlock());
      assertEquals(0, (int)element0.siblingIndex());
      assertEquals("LM3& Wv&'#I", element0.baseUri());
      assertNotNull(element0);
      
      // Undeclared exception!
      try { 
        document0.replaceChild(element0, element0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Document document0 = new Document("O\"1JX");
      assertEquals("#document", document0.nodeName());
      assertFalse(document0.isBlock());
      assertEquals("O\"1JX", document0.baseUri());
      assertEquals(0, (int)document0.siblingIndex());
      assertNotNull(document0);
      
      Element element0 = document0.appendElement("otimes");
      assertEquals("#document", document0.nodeName());
      assertFalse(document0.isBlock());
      assertEquals("O\"1JX", document0.baseUri());
      assertEquals(0, (int)document0.siblingIndex());
      assertEquals(0, (int)element0.siblingIndex());
      assertEquals("O\"1JX", element0.baseUri());
      assertFalse(element0.isBlock());
      assertNotNull(element0);
      
      document0.replaceChild(element0, document0);
      assertEquals("#document", document0.nodeName());
      assertFalse(document0.isBlock());
      assertEquals("O\"1JX", document0.baseUri());
      assertEquals(0, (int)document0.siblingIndex());
      assertEquals(0, (int)element0.siblingIndex());
      assertEquals("O\"1JX", element0.baseUri());
      assertFalse(element0.isBlock());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Document document0 = Document.createShell("/LdxW");
      assertEquals("#document", document0.nodeName());
      assertEquals(0, (int)document0.siblingIndex());
      assertFalse(document0.isBlock());
      assertEquals("/LdxW", document0.baseUri());
      assertNotNull(document0);
      
      // Undeclared exception!
      try { 
        document0.replaceChild(document0, document0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Must be true
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TextNode textNode0 = TextNode.createFromEncoded("/LdxW", "/LdxW");
      assertEquals("/LdxW", textNode0.baseUri());
      assertEquals("#text", textNode0.nodeName());
      assertEquals(0, (int)textNode0.siblingIndex());
      assertNotNull(textNode0);
      
      Document document0 = Document.createShell("/LdxW");
      assertEquals(0, (int)document0.siblingIndex());
      assertFalse(document0.isBlock());
      assertEquals("/LdxW", document0.baseUri());
      assertEquals("#document", document0.nodeName());
      assertNotNull(document0);
      
      Element element0 = document0.appendChild(textNode0);
      assertSame(document0, element0);
      assertSame(element0, document0);
      assertEquals("/LdxW", textNode0.baseUri());
      assertEquals("#text", textNode0.nodeName());
      assertEquals(1, (int)textNode0.siblingIndex());
      assertEquals(0, (int)document0.siblingIndex());
      assertFalse(document0.isBlock());
      assertEquals("/LdxW", document0.baseUri());
      assertEquals("#document", document0.nodeName());
      assertFalse(element0.isBlock());
      assertEquals(0, (int)element0.siblingIndex());
      assertEquals("/LdxW", element0.baseUri());
      assertEquals("#document", element0.nodeName());
      assertNotNull(element0);
      
      textNode0.setParentNode(element0);
      assertSame(document0, element0);
      assertSame(element0, document0);
      assertEquals("/LdxW", textNode0.baseUri());
      assertEquals("#text", textNode0.nodeName());
      assertEquals(1, (int)textNode0.siblingIndex());
      assertEquals(0, (int)document0.siblingIndex());
      assertFalse(document0.isBlock());
      assertEquals("/LdxW", document0.baseUri());
      assertEquals("#document", document0.nodeName());
      assertFalse(element0.isBlock());
      assertEquals(0, (int)element0.siblingIndex());
      assertEquals("/LdxW", element0.baseUri());
      assertEquals("#document", element0.nodeName());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TextNode textNode0 = new TextNode("abs:n 9jz$", "abs:n 9jz$");
      assertEquals(0, (int)textNode0.siblingIndex());
      assertEquals("abs:n 9jz$", textNode0.baseUri());
      assertEquals("#text", textNode0.nodeName());
      assertNotNull(textNode0);
      
      String string0 = textNode0.attr("abs:notinvc");
      assertEquals(0, (int)textNode0.siblingIndex());
      assertEquals("abs:n 9jz$", textNode0.baseUri());
      assertEquals("#text", textNode0.nodeName());
      assertNotNull(string0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TextNode textNode0 = new TextNode("={_u:J}73>ne-9o3", "={_u:J}73>ne-9o3");
      assertEquals("={_u:J}73>ne-9o3", textNode0.baseUri());
      assertEquals("#text", textNode0.nodeName());
      assertEquals(0, (int)textNode0.siblingIndex());
      assertNotNull(textNode0);
      
      Attributes attributes0 = textNode0.attributes();
      assertEquals("={_u:J}73>ne-9o3", textNode0.baseUri());
      assertEquals("#text", textNode0.nodeName());
      assertEquals(0, (int)textNode0.siblingIndex());
      assertNotNull(attributes0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TextNode textNode0 = TextNode.createFromEncoded("org.jsoup.nodes.Node$OuterHtmlVisitor", "org.jsoup.nodes.Node$OuterHtmlVisitor");
      assertEquals("org.jsoup.nodes.Node$OuterHtmlVisitor", textNode0.baseUri());
      assertEquals("#text", textNode0.nodeName());
      assertEquals(0, (int)textNode0.siblingIndex());
      assertNotNull(textNode0);
      
      String string0 = textNode0.toString();
      assertEquals("org.jsoup.nodes.Node$OuterHtmlVisitor", textNode0.baseUri());
      assertEquals("#text", textNode0.nodeName());
      assertEquals(0, (int)textNode0.siblingIndex());
      assertNotNull(string0);
      assertEquals("org.jsoup.nodes.Node$OuterHtmlVisitor", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      TextNode textNode0 = TextNode.createFromEncoded("/LdxW", "/LdxW");
      assertEquals("/LdxW", textNode0.baseUri());
      assertEquals(0, (int)textNode0.siblingIndex());
      assertEquals("#text", textNode0.nodeName());
      assertNotNull(textNode0);
      
      // Undeclared exception!
      try { 
        textNode0.remove();
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Object must not be null
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Document document0 = Document.createShell("$)+$");
      assertEquals("$)+$", document0.baseUri());
      assertEquals("#document", document0.nodeName());
      assertFalse(document0.isBlock());
      assertEquals(0, (int)document0.siblingIndex());
      assertNotNull(document0);
      
      String string0 = document0.toString();
      assertEquals("$)+$", document0.baseUri());
      assertEquals("#document", document0.nodeName());
      assertFalse(document0.isBlock());
      assertEquals(0, (int)document0.siblingIndex());
      assertNotNull(string0);
      assertEquals("<html>\n <head></head>\n <body></body>\n</html>", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Document document0 = Document.createShell("/Od>W");
      assertFalse(document0.isBlock());
      assertEquals("#document", document0.nodeName());
      assertEquals(0, (int)document0.siblingIndex());
      assertEquals("/Od>W", document0.baseUri());
      assertNotNull(document0);
      
      Document document1 = document0.clone();
      assertFalse(document1.equals((Object)document0));
      assertNotSame(document0, document1);
      assertNotSame(document1, document0);
      assertFalse(document0.isBlock());
      assertEquals("#document", document0.nodeName());
      assertEquals(0, (int)document0.siblingIndex());
      assertEquals("/Od>W", document0.baseUri());
      assertEquals("/Od>W", document1.baseUri());
      assertFalse(document1.isBlock());
      assertEquals(0, (int)document1.siblingIndex());
      assertEquals("#document", document1.nodeName());
      assertNotNull(document1);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      DataNode dataNode0 = new DataNode("org.jsoup.nodes.Node", "org.jsoup.nodes.Node");
      assertEquals("org.jsoup.nodes.Node", dataNode0.baseUri());
      assertEquals("#data", dataNode0.nodeName());
      assertEquals(0, (int)dataNode0.siblingIndex());
      assertNotNull(dataNode0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      TextNode textNode0 = new TextNode("/LidxW", "/LidxW");
      assertEquals("#text", textNode0.nodeName());
      assertEquals("/LidxW", textNode0.baseUri());
      assertEquals(0, (int)textNode0.siblingIndex());
      assertNotNull(textNode0);
      
      // Undeclared exception!
      try { 
        textNode0.siblingNodes();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.nodes.Node", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Document document0 = Document.createShell("d1.[$&WBzg\"xfF'rzF");
      assertEquals(0, (int)document0.siblingIndex());
      assertEquals("d1.[$&WBzg\"xfF'rzF", document0.baseUri());
      assertEquals("#document", document0.nodeName());
      assertFalse(document0.isBlock());
      assertNotNull(document0);
      
      // Undeclared exception!
      try { 
        document0.replaceWith(document0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Object must not be null
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Document document0 = new Document("O\"1JX");
      assertEquals(0, (int)document0.siblingIndex());
      assertFalse(document0.isBlock());
      assertEquals("O\"1JX", document0.baseUri());
      assertEquals("#document", document0.nodeName());
      assertNotNull(document0);
      
      Element element0 = document0.append("otimes");
      assertSame(document0, element0);
      assertSame(element0, document0);
      assertEquals(0, (int)document0.siblingIndex());
      assertFalse(document0.isBlock());
      assertEquals("O\"1JX", document0.baseUri());
      assertEquals("#document", document0.nodeName());
      assertEquals("O\"1JX", element0.baseUri());
      assertEquals(0, (int)element0.siblingIndex());
      assertEquals("#document", element0.nodeName());
      assertFalse(element0.isBlock());
      assertNotNull(element0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      TextNode textNode0 = new TextNode("rangd", "rangd");
      assertEquals("#text", textNode0.nodeName());
      assertEquals(0, (int)textNode0.siblingIndex());
      assertEquals("rangd", textNode0.baseUri());
      assertNotNull(textNode0);
      
      Node node0 = textNode0.removeAttr("rangd");
      assertSame(textNode0, node0);
      assertSame(node0, textNode0);
      assertEquals("#text", textNode0.nodeName());
      assertEquals(0, (int)textNode0.siblingIndex());
      assertEquals("rangd", textNode0.baseUri());
      assertEquals("#text", node0.nodeName());
      assertEquals("rangd", node0.baseUri());
      assertEquals(0, (int)node0.siblingIndex());
      assertNotNull(node0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      TextNode textNode0 = TextNode.createFromEncoded("/LdxW", "/LdxW");
      assertEquals("#text", textNode0.nodeName());
      assertEquals(0, (int)textNode0.siblingIndex());
      assertEquals("/LdxW", textNode0.baseUri());
      assertNotNull(textNode0);
      
      Node node0 = textNode0.attr("/LdxW", "/LdxW");
      assertSame(textNode0, node0);
      assertSame(node0, textNode0);
      assertEquals("#text", textNode0.nodeName());
      assertEquals(0, (int)textNode0.siblingIndex());
      assertEquals("/LdxW", textNode0.baseUri());
      assertEquals(0, (int)node0.siblingIndex());
      assertEquals("/LdxW", node0.baseUri());
      assertEquals("#text", node0.nodeName());
      assertNotNull(node0);
      
      String string0 = textNode0.absUrl("/LdxW");
      assertSame(textNode0, node0);
      assertEquals("#text", textNode0.nodeName());
      assertEquals(0, (int)textNode0.siblingIndex());
      assertEquals("/LdxW", textNode0.baseUri());
      assertNotNull(string0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      TextNode textNode0 = TextNode.createFromEncoded("/ELdx~", "/ELdx~");
      assertEquals("/ELdx~", textNode0.baseUri());
      assertEquals(0, (int)textNode0.siblingIndex());
      assertEquals("#text", textNode0.nodeName());
      assertNotNull(textNode0);
      
      // Undeclared exception!
      try { 
        textNode0.setBaseUri((String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Object must not be null
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }
}
